apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: mycertmanager
spec:
  destination:
    namespace: mycertmanager
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: cert-manager
    helm:
      parameters:
        - name: installCRDs
          value: "true"
        - name: podLabels.azure.workload.identity/use
          value: "true"
        - name: serviceAccount.labels.azure.workload.identity/use
          value: "true"
    repoURL: https://charts.jetstack.io
    targetRevision: v1.3.1
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
